stages:
  - build
  - test

cache:
  key: node_modules
  paths:
    - .npm/

before_script:
  - \[ -d "../vetprovieh-shared/" ] && rm -R ../vetprovieh-shared/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-shared ../vetprovieh-shared
  - \[ -d "../formt-validation/" ] && rm -R ../formt-validation/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/formt-validation ../formt-validation
  - npm ci --cache .npm --prefer-offline
  
build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npm run test
